# Generated by Django 2.2 on 2019-05-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=30, verbose_name='代理商代号')),
                ('company', models.CharField(max_length=30, verbose_name='培训人名称')),
                ('phone', models.CharField(max_length=30, verbose_name='手机号')),
                ('area', models.CharField(max_length=30, verbose_name='区域')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
        ),
    ]
